"use client";
import { usePathname } from 'next/navigation';
import Navbar from '../components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = usePathname();
 
  return (
    <html lang="en">
        <body className={inter.className}>
          {
          router !== "/" && router 
          !== "/login" && router
          !== "/register" && <Navbar />
          }
          {children}</body>
    </html>
  )
}
